// Date: 12-10-2015 10:22:31
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class Modelironskullcap extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
  
  public Modelironskullcap()
  {
    textureWidth = 256;
    textureHeight = 64;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 24, 6, 24);
      Shape1.setRotationPoint(-6F, -9F, -6F);
      Shape1.setTextureSize(256, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 96, 0);
      Shape2.addBox(0F, 0F, 0F, 22, 4, 22);
      Shape2.setRotationPoint(-5F, -13F, -5F);
      Shape2.setTextureSize(256, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 184, 0);
      Shape3.addBox(0F, 0F, 0F, 6, 8, 7);
      Shape3.setRotationPoint(3F, -10F, 13F);
      Shape3.setTextureSize(256, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 211, 0);
      Shape4.addBox(0F, 0F, 0F, 2, 9, 20);
      Shape4.setRotationPoint(-5F, -3F, -5F);
      Shape4.setTextureSize(256, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 31);
      Shape5.addBox(0F, 0F, 0F, 2, 9, 20);
      Shape5.setRotationPoint(15F, -3F, -5F);
      Shape5.setTextureSize(256, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 47, 31);
      Shape6.addBox(0F, 0F, 0F, 18, 10, 2);
      Shape6.setRotationPoint(-3F, -3F, -5F);
      Shape6.setTextureSize(256, 64);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 99, 28);
      Shape7.addBox(0F, 0F, 0F, 20, 3, 20);
      Shape7.setRotationPoint(-4F, -16F, -4F);
      Shape7.setTextureSize(256, 64);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 185, 18);
      Shape8.addBox(0F, 0F, 0F, 6, 10, 6);
      Shape8.setRotationPoint(3F, -6F, 16F);
      Shape8.setTextureSize(256, 64);
      Shape8.mirror = true;
      setRotation(Shape8, -0.4833219F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
